/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.databits3883.databitslib;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
